<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net8.0-windows10.0.19041.0</TargetFramework>
		<UseWPF>true</UseWPF>
		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>
		<AssemblyName>WDesk.Widgets.Prayer</AssemblyName>
		<RootNamespace>WDesk.Widgets.Prayer</RootNamespace>
		<Version>1.0.0</Version>
		<EnableDynamicLoading>true</EnableDynamicLoading>
	</PropertyGroup>

	<!-- ★ این باید WDesk.SDK باشه، نه WDesk -->
	<ItemGroup>
		<ProjectReference Include="..\WDesk.SDK\WDesk.SDK.csproj">
			<Private>false</Private>
			<ExcludeAssets>runtime</ExcludeAssets>
		</ProjectReference>
	</ItemGroup>

	<ItemGroup>
		<None Update="manifest.json">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</None>
	</ItemGroup>

</Project>